let peliculas = [{
        "id": 1,
        "imagenSrc": "../images/peliculas/peli-1.jpg",
        "imagenAlt": "Foto de The Usual Suspects",
        "nombre": "The Usual Suspects",
        "genero": "Suspense",
        "anio": 1995,
        "precio": 100,
        "vendido": false,
    },
    {
        "id": 2,
        "imagenSrc": "../images/peliculas/peli-2.jpg",
        "imagenAlt": "Foto de Pulp Fiction",
        "nombre": "Pulp Fiction",
        "genero": "Acción",
        "anio": 1994,
        "precio": 100,
        "vendido": false,
    },
    {
        "id": 3,
        "imagenSrc": "../images/peliculas/peli-3.jpg",
        "imagenAlt": "Foto de El hijo de la novia",
        "nombre": "El hijo de la novia",
        "genero": "Drama",
        "anio": 2001,
        "precio": 95,
        "vendido": false,
    },
    {
        "id": 4,
        "imagenSrc": "../images/peliculas/peli-4.jpg",
        "imagenAlt": "Foto de Big Fish",
        "nombre": "Big Fish",
        "genero": "Fantasía",
        "anio": 2003,
        "precio": 95,
        "vendido": false,
    },
    {
        "id": 5,
        "imagenSrc": "../images/peliculas/peli-5.jpg",
        "imagenAlt": "Foto de Love Actually",
        "nombre": "Love Actually",
        "genero": "Comedia",
        "anio": 2003,
        "precio": 95,
        "vendido": false,
    },
    {
        "id": 6,
        "imagenSrc": "../images/peliculas/peli-6.jpg",
        "imagenAlt": "Foto de There Will Be Blood",
        "nombre": "There Will Be Blood",
        "genero": "Drama",
        "anio": 2007,
        "precio": 95,
        "vendido": false,
    },
    {
        "id": 7,
        "imagenSrc": "../images/peliculas/peli-7.jpg",
        "imagenAlt": "Foto de La suerte está echada",
        "nombre": "La suerte está echada",
        "genero": "Comedia",
        "anio": 2005,
        "precio": 95,
        "vendido": false,
    },
    {
        "id": 8,
        "imagenSrc": "../images/peliculas/peli-8.jpg",
        "imagenAlt": "Foto de Psycho",
        "nombre": "Psycho",
        "genero": "Suspense",
        "anio": 1960,
        "precio": 105,
        "vendido": false,
    },
    {
        "id": 9,
        "imagenSrc": "../images/peliculas/peli-9.jpg",
        "imagenAlt": "Foto de The Hunt",
        "nombre": "The Hunt",
        "genero": "Drama",
        "anio": 2012,
        "precio": 95,
        "vendido": false,
    },
    {
        "id": 10,
        "imagenSrc": "../images/peliculas/peli-10.jpg",
        "imagenAlt": "Foto de Whiplash",
        "nombre": "Whiplash",
        "genero": "Drama",
        "anio": 2014,
        "precio": 95,
        "vendido": false,
    },
    {
        "id": 11,
        "imagenSrc": "../images/peliculas/peli-11.jpg",
        "imagenAlt": "Foto de La dolce vita",
        "nombre": "La dolce vita",
        "genero": "Drama",
        "anio": 1960,
        "precio": 105,
        "vendido": false,
    },
    {
        "id": 12,
        "imagenSrc": "../images/peliculas/peli-12.jpg",
        "imagenAlt": "Foto de Forrest Gump",
        "nombre": "Forrest Gump",
        "genero": "Drama",
        "anio": 1994,
        "precio": 100,
        "vendido": false,
    },
]